### PR TITLE
Remove version.properties and increment version number manually instead

### PR DESCRIPTION
**Pull request by BBaoVanC**
It doesn't make sense to have it automatically increment the version number of the program every single time you compile it. The version should only increase if any changes were made to the program. This program gets annoying to work on quickly when the build number keeps incrementing every time I compile it to test a change.

I also think it's best to use [semantic versioning](https://semver.org/) instead of an arbitrary build number for releases.

### CODE REVIEW

**Comment by BBaoVanC** [comment]
Another thing I noticed while working on this, it looks like there's a `shadowJar` task, but it doesn't seem to be needed? I was building it normally without any shadowing and it worked fine on the latest Velocity dev version.

**Comment by BBaoVanC** [comment]
I made a [`remove-shadowjar-task`](https://github.com/BBaoVanC/velocity-chat/tree/remove-shadowjar-task) which is based off of this PR. and it seems to work exactly the same. If you want I could make a PR for it too.

**Comment by confor** [comment]
hi, both of the issues you mention exist because i don't know enough about the minecraft java ecosytem to understand how things are done. using incremental numbers seemed like a good choice because i could quickly test in my ide (which didn't increment the number) and then compile once to publish a .jar, but honestly i'd love to use semver.
i don't know what shadowjars are but i guess i'll search a bit. if the plugin works without them, then feel free to remove them in a pr. thank you for contributing btw!

**Comment by BBaoVanC** [comment]
No problem, I switched my server to this plugin instead of an abandoned gChat fork so I'm just fixing things as I go.

It looks like shadowJar was added so the latest version of mini message could be bundled, but now Velocity bundles an up to date version so its probably not needed. I'll make a PR soon.

**Pull request merged**
